---
:help: true
:folders:
  :jurisdictions: spec/tmp/spec/tmp/jurisdictions
  :sources: spec/tmp/spec/tmp/sources
  :downloads: spec/tmp/spec/tmp/downloads
  :datasets: spec/tmp/spec/tmp/datasets
:sources:
  :heydan_sources: git@github.com:danmelton/heydan_sources.git
